### ISSUE TITLE
How would you use idempotency_key ?

### ISSUE THREAD

**Issue by InstanceOfMichael** [thephpleague/omnipay-stripe#33]
https://stripe.com/docs/api#idempotent_requests

```
\Stripe\Charge::create(array(
  "amount" => 400,
  "currency" => "usd",
  "source" => "tok_16WQ672eZvKYlo2CBqe851Hy", // obtained with Stripe.js
  "description" => "Charge for test@example.com"
), array(
  "idempotency_key" => "96rNdGLJrIvJan5X",
));
```

which comes out as a header `Idempotency-Key: 96rNdGLJrIvJan5X`

**Comment by cfreear** [comment]
While I realise you may have found your answer by now I though I would still answer in case anyone else comes across this question.

To quote [stripe's docs](https://stripe.com/docs/api/php#idempotent_requests):
> To safely retry an API request without accidentally performing the same operation twice, you can attach a unique key to any POST request made to the Stripe API via the Idempotency-Key: <key> header.
> For example, if a request to create a charge fails due to a network connection error, you can make a second request with the same key to guarantee that only a single charge is created.
> The creation of the key is completely up to you — we suggest using random strings or UUIDs. We'll always send back the same response for requests made with the same key, even if you make the request with different request parameters. The keys expire after 24 hours.

As they suggest, don't generate a new idempotency key for each request instead use something that uniquely identifies the charge you are making so that no matter how many times you make that request it will only be processed by Stripe once.

P.S. this isn't really an omnipay related query, you may have had better luck asking on stack overflow.

**Comment by InstanceOfMichael** [comment]
I know how to use this without omnipay, I'm asking how to use it with omnipay.

**Comment by cfreear** [comment]
omnipay-stripe doesn't currently support idempotency keys. Pull requests would be welcome though.

**Comment by mscotto** [comment]
@InstanceOfMichael did you ever figure out a way to pass the key in the header?

**Comment by InstanceOfMichael** [comment]
> @InstanceOfMichael did you ever figure out a way to pass the key in the header?

My API calls via Omnipay make no attempt to do that. I am using it for some API calls outside the scope of Omnipay.
