### ISSUE TITLE
Cannot perform transaction based upon Stripe customer ID

### ISSUE THREAD

**Issue by radean0909** [thephpleague/omnipay-stripe#6]
It is possible to create cards (which then creates a Stripe customer) but after the customer is created, a transaction using the customer ID as the token isn't successful. Passing in the parameter 'customer' instead of token results in a card error being thrown stating that card details need to be passed.

Ideally, you should be able to pass a customer id and perform the transaction according to Stripe's payment API using the customer data instead of a token.

**Comment by delatbabel** [comment]
Both of the above issues are fixed in PR #13 . I have added separate createCard and createCustomer requests, and you can use createCard to add a card to an existing customer.  You now require both a customer reference and a card reference to complete a purchase or authorize transaction, as per the Stripe documentation.

**Comment by delatbabel** [comment]
This can be closed now, PR #13 has been merged.
