### ISSUE TITLE
Cannot install via Composer (404 Not Found)

### ISSUE THREAD

**Issue by MisterPoppet** [thephpleague/omnipay-stripe#9]
I'm getting this error anytime I try installing via composer. This is the error I get:
```
[Composer\Downloader\TransportException]                                     
The "https://api.github.com/repos/omnipay/stripe/zipball/e56ad2d1a7a50bacca  
727e1363aca44e35cf2573" file could not be downloaded (HTTP/1.1 404 Not Found)
```
This also happens for TargetPay, but that's a lesser priority.

**Comment by cfreear** [comment]
What are you using to require omnipay-stripe in your composer.json?

Using:
```json
{
    "require": {
        "omnipay/stripe": "~2.0"
    }
}
```
will attempt to download the release zipball but fail because the latest release still points to the old omnipay/stripe repository but it will then attempt to clone the repository directly for that release tag and the repository link on packagist correctly points to the thephpleague/omnipay-stripe repository and it succeeds.

**Comment by MisterPoppet** [comment]
I am requiring it the same way as in your example. When I update it only tries the zipball and not the source. I can only update by source if I trigger --prefer-source. So I'm considering this a composer issue. Thanks!
